server:
  port: 13000
spring:
  application:
    name: infrastructure-gateway
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 121.40.186.104:8848
        namespace: 2667ea5c-40e8-4a90-b321-01d799f0ff12
    gateway:
      routes:
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
          - Query=url,baidu
        - id: youtube_route
          uri: https://www.youku.com
          predicates:
          - Query=url,youku
